version: '3'

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment: 
      REACT_APP_API_URL: "http://localhost:5000/"
    command: yarn start
    volumes:
     - ./ui:/work
    ports:
     - "3000:3000"
    depends_on:
      - api

  api:
    build:
      context: ./backend
    command: python main.py
    ports:
     - "5000:5000"
